package main

import "html/template"

type launcherForm struct{ Host, Port, User, Database, TLS string }
type launcherPageData struct {
	Message, Nonce, Log, Phase, URL string
	Form                            launcherForm
	Error                           bool
}

var launcherPage = template.Must(template.New("setup").Parse(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ARTEX 启动器</title>{{if eq .Phase "starting"}}<meta http-equiv="refresh" content="2;url=/">{{end}}<style>
*{box-sizing:border-box}body{margin:0;background:#f7f7f8;color:#202124;font:15px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif}main{max-width:620px;margin:7vh auto;padding:24px}.card{background:white;border:1px solid #e4e4e7;border-radius:14px;padding:30px;box-shadow:0 3px 16px #00000005}h1{font-size:25px;margin:0 0 5px;letter-spacing:1px}.sub{color:#71717a;margin:0 0 24px}.status{padding:12px 16px;border-radius:8px;background:#f4f4f5;margin:18px 0}.error{background:#fff1f2;color:#9f1239}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.wide{grid-column:1/-1}label{display:block;font-size:13px;color:#52525b}input,select{width:100%;margin-top:6px;padding:10px 12px;border:1px solid #d4d4d8;border-radius:7px;font:inherit;background:white;color:#202124}input:focus,select:focus{outline:2px solid #a1a1aa;outline-offset:1px}button,.button{display:inline-block;border:1px solid #18181b;border-radius:7px;background:#18181b;color:white;font:inherit;text-decoration:none;padding:10px 18px;cursor:pointer}.secondary{background:white;color:#52525b;border-color:#d4d4d8}.actions{display:flex;gap:10px;align-items:center;margin-top:22px}.hint{font-size:13px;color:#71717a;margin:18px 0 0}.log{overflow-wrap:anywhere;font:12px/1.6 ui-monospace,monospace}.stop{margin:0}@media(max-width:520px){main{padding:16px;margin:3vh auto}.card{padding:22px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body><main><div class="card"><h1>ARTEX</h1><p class="sub">本地启动器</p><div class="status {{if .Error}}error{{end}}" role="status">{{.Message}}</div>{{if eq .Phase "setup"}}<form method="post"><input type="hidden" name="nonce" value="{{.Nonce}}"><div class="grid"><label>数据库主机<input name="host" value="{{.Form.Host}}" required placeholder="localhost"></label><label>端口<input name="port" value="{{.Form.Port}}" type="number" min="1" max="65535" required></label><label>用户名<input name="user" value="{{.Form.User}}" required autocomplete="username"></label><label>密码<input type="password" name="password" autocomplete="off"></label><label class="wide">数据库名称<input name="database" value="{{.Form.Database}}" required></label><label class="wide">连接安全<select name="tls"><option value="auto" {{if eq .Form.TLS "auto"}}selected{{end}}>自动：本地关闭 TLS，远程验证 TLS</option><option value="verify-full" {{if eq .Form.TLS "verify-full"}}selected{{end}}>验证 TLS 证书及主机名</option><option value="disable" {{if eq .Form.TLS "disable"}}selected{{end}}>关闭 TLS（仅本地数据库）</option></select></label></div><div class="actions"><button type="submit">连接并启动</button></div><p class="hint">请使用已有的 PostgreSQL 数据库。此处只检查连接，启动 ARTEX 后会初始化所需数据表。</p></form>{{else}}<div class="actions">{{if eq .Phase "running"}}<a class="button" href="{{.URL}}">打开 ARTEX</a>{{end}}<form class="stop" method="post" action="/stop"><input type="hidden" name="nonce" value="{{.Nonce}}"><button class="secondary">停止 ARTEX</button></form></div>{{end}}{{if eq .Phase "setup"}}<div class="actions"><form class="stop" method="post" action="/stop"><input type="hidden" name="nonce" value="{{.Nonce}}"><button class="secondary">关闭启动器</button></form></div>{{end}}{{if .Error}}<p class="hint">后端日志</p><p class="log">{{.Log}}</p>{{end}}<p class="hint">启动器仅在本机运行。也可使用 <code>artex launch stop</code> 停止。</p></div></main></body></html>`))
